# 나이브 베이즈


- 타겟 변수  y 의 각 클래스 {C1,⋯,CK}  에 대한 독립 변수  x 의 조건부 확률 분포 정보  p(x∣y=Ck)  를 사용하여 주어진 새로운 독립 변수 값  x에 대한 타켓 변수의 각 클래스의 조건부 확률  p(y=Ck∣x) 를 추정한 후 가장 조건부 확률이 큰 클래스  k 를 선택하는 방법이다.

---

연속적인 값을 지닌 데이터를 처리 할때, 전형적으로 각 클래스의 연속적인 값들이 가우스 분포를 따른다고 가정한다. 

smoothing : 분자에 1같은 수를 더하는 것.

나이브베이즈의 분류.
y가 0일때
y가 1일때
타원을 그리고 있으면 multivariate 가우시안 정규분포이다. QDA
Covariance Mat이 같을 경우 LDA가 된다.
나이브베이즈 x1 따소 그려서 히스토그램. mu, sigma값구해서 곱한걸로 어떤 방식이 보인다.

---

QDA->NB
QDA->LBA 
만차원. x100개= 100만개의 스칼라/숫자/정보/데이터.
-Corr mat구하면. 만개 * 만개 = 10^8 억개.
-약 1::100으로 정보가 쪼개진다
-100만화소라면 10^6 * 10^6 = 10^12
-Portfolio Optimization - 수익률 , 주식과 주식의 corr mat - 아무의미가 없다.
-너무 많으면 noise. Corr Estimation 이 흔들린다. 숫자가 작다.

----
나이브  - 1)가우시안 

2)베르누이

y클래스 별로.
x= 0,1 Bern 동전 나온 갯수 / 1이 나온갯수 = theta 추정.
x1 = y=1 theta 1 y=0 theta2
y = 20, 10000개 -> 20만개 추정.
스무딩 - 내가 실제로 구해보니까 5번 던져서 3면이 앞면이 나왔다면 보너스 데이터를 하나씩 나올수 있는 경우(0,1이면 2개) 를 준다. 그래서 7개 중에 4개로 하는거다.1이나 0이란 극단적인 값은 피하기 위해서. 보너스 1이면 알파 1.
보너스를 주면 주는만큼
----
P(x1)~ 식으로 상관관계 없다는 것끼리 쪼개기. 숫자가 하나의 박스에서 (주사위를 던져서 나온1 ,2,3,4,횟수 - 서로 상관관계가 없는것.)에서 나오면 multinomial (n번 던져서) 
쪼갤때 P(x1,x2,x3,x4) 안째고 theta1,theta2~의 확률을 계산한다. 이중에서 어떤게 더 많이 나올까 알아내는게 multi-norm 분포.

x1 = (0,1,2,3) , x2 = (2,5,2,4)
x1 = 4면체 주사위인데 1이란게 1번도 안나왔고 2는 1번 3번째 2번 4번째 3번. 주사위는 6번 던져짐.
x2 = 10번던짐.
x마다 나온횟수(n)이 같을 필요는 없다. 왜냐하면 전체 횟수를 가지고 계산할 것이기때문에.
smoothing(가짜 데이터 1,1,1,1) 추가.
likelihood 식 구함.
multinomial 식 : p(x|y)
구하고자 하는것 : p(x|y)*사전.
---




In [6]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report, roc_curve
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_iris
from sklearn.preprocessing import label_binarize
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
import statsmodels.api as sm
import pandas as pd
import seaborn as sns
import statsmodels.formula.api as smf
import scipy as sp
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt


In [2]:
# 다항 분포 나이브 베이즈 모형
np.random.seed(0)
#주사위 4면 10번
X0 = np.random.multinomial(10, [0.3, 0.5, 0.1, 0.1], size=4)
#주사위 6면짜리 8번
X1 = np.random.multinomial(8, [0.1, 0.1, 0.35, 0.45], size=6)
X = np.vstack([X0, X1])
y = np.array([0,0,0,0,1,1,1,1,1,1])
print(X)
print(y)

[[3 4 1 2]
 [3 5 1 1]
 [3 3 0 4]
 [3 4 1 2]
 [1 2 1 4]
 [0 0 5 3]
 [1 2 4 1]
 [1 1 4 2]
 [0 1 2 5]
 [2 1 2 3]]
[0 0 0 0 1 1 1 1 1 1]


In [22]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
clf_bern = BernoulliNB().fit(X, y)
clf_mult = MultinomialNB().fit(X, y)
clf_mult.classes_ #2개 y= 0과 1

array([0, 1])

In [14]:
clf_mult.class_count_

array([ 4.,  6.])

In [8]:
clf_mult = MultinomialNB().fit(X,y)
# y = 0 or 1
clf_mult.classes_
# 4면, 6면
clf_mult.class_count_
# feature 갯수, 분자. 1일때 12개 2일때 16개 등...
clf_mult.feature_count_

array([[ 12.,  16.,   3.,   9.],
       [  5.,   7.,  18.,  18.]])

In [6]:
clf_mult.class_count_ #주사위 면

array([ 4.,  6.])

In [16]:
# feature 갯수. 분자. feature counts
fc = clf_mult.feature_count_
fc

array([[ 12.,  16.,   3.,   9.],
       [  5.,   7.,  18.,  18.]])

In [14]:
fc / np.repeat(fc.sum(axis=1)[:, np.newaxis], 4, axis=1)

array([[ 0.3       ,  0.4       ,  0.075     ,  0.225     ],
       [ 0.10416667,  0.14583333,  0.375     ,  0.375     ]])

In [30]:
denom = np.repeat(fc.sum(axis = 1)[:, np.newaxis], 4, axis = 1)
# 4*10 = 40 / 6*8 = 48
# Denominator = denom 분모
denom

array([[ 40.,  40.,  40.,  40.],
       [ 48.,  48.,  48.,  48.]])

In [37]:
# Pyx = Pxy*Py / Px
# Smooth 전.Pyx (나이브베이즈)
Pxy = fc
Pyx = Pxy / denom
Pyx 

array([[ 0.3       ,  0.4       ,  0.075     ,  0.225     ],
       [ 0.10416667,  0.14583333,  0.375     ,  0.375     ]])

In [38]:
#Smooth 하기 위해 alpha 생성 
a = clf_mult.alpha
a

1.0

In [77]:
(Pxy + clf_mult.alpha) / \
(np.repeat(fc.sum(axis=1)[:, np.newaxis], 4, axis=1) + \
                          clf_mult.alpha * X.shape[1])

array([[ 0.29545455,  0.38636364,  0.09090909,  0.22727273],
       [ 0.11538462,  0.15384615,  0.36538462,  0.36538462]])

In [79]:
#X.shape[1] = 4
Px = denom + a*X.shape[1]
Pyx_smooth = Pxy + a / denom + a*X.shape[1]
print(Pxy + a)
print(Px)
# Pyx_smooth = Pxy + a / Px 
#이지만 백터이기때문에 단순하게 곱셈나눗셈 식으로 연산 못함 .
#결론.
(Pxy + clf_mult.alpha) / \
(np.repeat(fc.sum(axis=1)[:, np.newaxis], 4, axis=1) + \
                          clf_mult.alpha * X.shape[1])


[[ 13.  17.   4.  10.]
 [  6.   8.  19.  19.]]
[[ 44.  44.  44.  44.]
 [ 52.  52.  52.  52.]]


array([[ 0.29545455,  0.38636364,  0.09090909,  0.22727273],
       [ 0.11538462,  0.15384615,  0.36538462,  0.36538462]])

In [28]:
# 나이브베이즈.
# 단번에 구하기 THETA = Pyx_smooth
# clf_mult = MultinomialNB().fit(X,y)
theta = np.exp(clf_mult.feature_log_prob_)
theta

array([[ 0.29545455,  0.38636364,  0.09090909,  0.22727273],
       [ 0.11538462,  0.15384615,  0.36538462,  0.36538462]])

In [29]:
x_new = np.array([10, 10, 10, 10])
clf_mult.predict_proba([x_new])

array([[ 0.38848858,  0.61151142]])

In [30]:
p = (theta**x_new).prod(axis=1)*np.exp(clf_bern.class_log_prior_)
p / p.sum()

array([ 0.38848858,  0.61151142])